name: main-bun
jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          bun-version: latest
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun index.ts
      - run: bun run build
